# Generated by Django 4.2.4 on 2024-11-24 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default-profile.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
