# Generated by Django 4.2.4 on 2024-12-02 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_tag_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='category',
        ),
    ]
